stages:
  - build-npm

.build:
  script:
    - npm run install-dev
    - npm run build

.set-names:
  script:
    - 'sed -i "s/\"name\": \".*\"/\"name\": \"$NAME\"/g" package.json'
    - 'sed -i "s/\"version\": \".*\"/\"version\": \"$TAG\"/g" package.json'

.upload-gitlab-registry:
  script:
    - echo "@cthulhu:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/">.npmrc
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
    - npm publish


build-npm-dev:
  stage: build-npm
  only:
    - master
  image: node
  script:
    - ls -l frontend/src
    - !reference [.build, script]
    - export NAME="@cthulhu\/dev"
    - export TAG="0.$(date +"%Y%m%d.%H%M%S")"
    - !reference [.set-names, script]
    - !reference [.upload-gitlab-registry, script]
  
build-npm:
  stage: build-npm
  only:
    - tags
  image: node
  script:
    - !reference [.build, script]
    - export NAME="@cthulhu\/stable"
    - export TAG=$CI_COMMIT_TAG
    - !reference [.set-names, script]
    - !reference [.upload-gitlab-registry, script]
    - export NAME="cthulhu"
    - export TAG=$CI_COMMIT_TAG
    - !reference [.set-names, script]
    #ToDo: Add deployment to npmjs.com
