stages:
  - build-npm

build-npm-dev:
  stage: build-npm
  only:
    - master
  image: node
  before_script:
    - export NAME="@cthulhu/cthulhu-dev"
    - export TAG="0.$(date +"%Y%m%d.%H%M%S")"
  script:
    - npm run install-dev
    - npm run build
    - 'sed -i "s/\"name\": \".*\"/\"name\": \"$NAME\"/g" package.json'
    - 'sed -i "s/\"version\": \".*\"/\"version\": \"$TAG\"/g" package.json'
    - echo "@cthulhu:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/">.npmrc
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
    - npm publish
  
build-npm:
  stage: build-npm
  only:
    - tags
  image: node
  before_script:
    - export NAME="cthulhu"
    - export TAG=$CI_COMMIT_TAG
  script:
    - !reference [build-npm-dev, script]
    #ToDo: Add deployment to npmjs.com
