stages:
  - build-npm

build-npm-dev:
  stage: build-npm
  only:
    - master
  image: node
  before_script:
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
  script:
    - npm run install-dev
    - npm run build
    - npm publish --tag "build_$(date +"%Y%m%d-%H%M%S")"